using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PropulsionPower : ResourceDef
{
    public override string DefName => "PropulsionPower";
    public override string Label => "propulsion power";
    public override string Description => "The total force generated by your engines this turn. 1 PP moves 1,000 kg of train weight up to 10 km on flat ground. Heavier trains or tough terrain reduce the distance traveled.";
}
